import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
const command = process.argv.slice(2).join(" ") || "open news.ycombinator.com and scroll down";
const transport = new StdioClientTransport({ command: "npx", args: ["tsx", "server/mcp.ts"], env: { ...process.env }, cwd: process.cwd() });
const client = new Client({ name: "smoke", version: "0" });
await client.connect(transport);
console.log("tools:", (await client.listTools()).tools.map((t) => t.name).join(", "));
const r = await client.callTool({ name: "jev_browse", arguments: { command } });
console.log(r.content[0].text);
await client.close();
